/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package bitmap.transformer;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Arrays;
public class App {
    public static void main(String[] args) throws IOException {

        String inputFilePath = args[0];
        String outputFilePath = args[1];
        String transformName = args[2];
        int width = Integer.parseInt(args[3]);
        int height = Integer.parseInt(args[4]);


        Bitmap bitmap = new Bitmap(inputFilePath);

        switch (transformName) {
            case "FlipVertical":
                bitmap.flipVertically();
                break;
            case "ChangeSize":
               bitmap.resizeImage(width, height);
                break;
           case "AddBorder":
                bitmap.addBorder();
             break;
            default:
                System.err.println("Invalid transform name.");
                return;
        }
        bitmap.saveImage(outputFilePath);
        System.out.println("Transform completed. Output saved to " + outputFilePath);
    }
}